{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Jan 26 12:16:33 2018) by ROOT version5.34/36
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0.4814815,nan,4.185185,nan);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.14);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.16);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1D *s_Kpipi_unmixed_p__1 = new TH1D("s_Kpipi_unmixed_p__1","",10,1,4);
   s_Kpipi_unmixed_p__1->SetBinContent(0,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(1,1);
   s_Kpipi_unmixed_p__1->SetBinContent(2,1);
   s_Kpipi_unmixed_p__1->SetBinContent(3,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(4,-1);
   s_Kpipi_unmixed_p__1->SetBinContent(5,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(6,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(7,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(8,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(9,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(10,nan);
   s_Kpipi_unmixed_p__1->SetBinContent(11,nan);
   s_Kpipi_unmixed_p__1->SetBinError(1,1e-100);
   s_Kpipi_unmixed_p__1->SetMinimum(-0.5);
   s_Kpipi_unmixed_p__1->SetMaximum(0.5);
   s_Kpipi_unmixed_p__1->SetEntries(11.16667);
   s_Kpipi_unmixed_p__1->SetDirectory(0);
   s_Kpipi_unmixed_p__1->SetStats(0);
   s_Kpipi_unmixed_p__1->SetLineWidth(2);
   s_Kpipi_unmixed_p__1->SetMarkerStyle(20);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetTitle("#left[m^{2}(K^{+} #pi^{+} #pi^{-})#right] (GeV^{2}/c^{4})");
   s_Kpipi_unmixed_p__1->GetXaxis()->SetRange(1,40);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetNdivisions(505);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetLabelOffset(0.01);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetTitleOffset(0.95);
   s_Kpipi_unmixed_p__1->GetXaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetTitle("Events (norm.) ");
   s_Kpipi_unmixed_p__1->GetYaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetLabelOffset(0.01);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetTitleOffset(1.02);
   s_Kpipi_unmixed_p__1->GetYaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p__1->GetZaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p__1->GetZaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p__1->GetZaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p__1->GetZaxis()->SetTitleOffset(1.2);
   s_Kpipi_unmixed_p__1->GetZaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p__1->Draw("e");
   
   TH1D *s_Kpipi_unmixed_p_fit__2 = new TH1D("s_Kpipi_unmixed_p_fit__2","",10,1,4);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(0,0.2051195);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(1,0.111236);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(2,0.08929074);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(3,0.09179091);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(4,0.03131327);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(5,0.09184476);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(6,0.04665722);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(7,0.1903159);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(8,0.2048489);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(9,-0.4626452);
   s_Kpipi_unmixed_p_fit__2->SetBinContent(10,0.4630459);
   s_Kpipi_unmixed_p_fit__2->SetBinError(0,0.4477575);
   s_Kpipi_unmixed_p_fit__2->SetBinError(1,0.09637656);
   s_Kpipi_unmixed_p_fit__2->SetBinError(2,0.02555462);
   s_Kpipi_unmixed_p_fit__2->SetBinError(3,0.02127514);
   s_Kpipi_unmixed_p_fit__2->SetBinError(4,0.03898997);
   s_Kpipi_unmixed_p_fit__2->SetBinError(5,0.05994238);
   s_Kpipi_unmixed_p_fit__2->SetBinError(6,0.07854337);
   s_Kpipi_unmixed_p_fit__2->SetBinError(7,0.09896814);
   s_Kpipi_unmixed_p_fit__2->SetBinError(8,0.1104598);
   s_Kpipi_unmixed_p_fit__2->SetBinError(9,0.1373959);
   s_Kpipi_unmixed_p_fit__2->SetBinError(10,0.1640908);
   s_Kpipi_unmixed_p_fit__2->SetBinError(11,0.2472561);
   s_Kpipi_unmixed_p_fit__2->SetEntries(15.36333);
   s_Kpipi_unmixed_p_fit__2->SetDirectory(0);
   s_Kpipi_unmixed_p_fit__2->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   s_Kpipi_unmixed_p_fit__2->SetLineColor(ci);
   s_Kpipi_unmixed_p_fit__2->SetLineWidth(2);
   s_Kpipi_unmixed_p_fit__2->SetMarkerStyle(20);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetTitle("#left[m^{2}(K^{+} #pi^{+} #pi^{-})#right] (GeV^{2}/c^{4})");
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetRange(1,40);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetNdivisions(505);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetLabelOffset(0.01);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetTitleOffset(0.95);
   s_Kpipi_unmixed_p_fit__2->GetXaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetTitle("Events (norm.) ");
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetLabelOffset(0.01);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetTitleOffset(1.02);
   s_Kpipi_unmixed_p_fit__2->GetYaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p_fit__2->GetZaxis()->SetLabelFont(132);
   s_Kpipi_unmixed_p_fit__2->GetZaxis()->SetLabelSize(0.06);
   s_Kpipi_unmixed_p_fit__2->GetZaxis()->SetTitleSize(0.072);
   s_Kpipi_unmixed_p_fit__2->GetZaxis()->SetTitleOffset(1.2);
   s_Kpipi_unmixed_p_fit__2->GetZaxis()->SetTitleFont(132);
   s_Kpipi_unmixed_p_fit__2->Draw("histcsame");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
